Add NavigationCard constants
lelandrichardson/react-native-mock pull request #107
Opened 2016-10-26 15:33 UTC by dingbat

Currently any use with [react-router-native](https://github.com/jmurzy/react-router-native) fails because it expects several classes/functions to be defined on `NavigationExperimental.Card` (see in react-native [here](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCard.js#L127-L130)).

It also expects `forHorizontal` and `forVertical` in `CardStackStyleInterpolator` and `forHorizontal` in `PagerStyleInterpolator`, all on load.

This PR adds all those mocks to the existing NavigationExperimental mock.

Thanks for the hard work put into this library!

2016-10-26 18:26 UTC, RealOrangeOne requested changes
With something like this, don't use createMockComponent, it's only designed for simple things. Just create a simple react component class

2016-10-26 18:53 UTC, dingbat commented
@RealOrangeOne Lint wanted it written as a stateless function. Let me know what you think.

2016-10-27 08:13 UTC, RealOrangeOne commented
@dingbat I understand why. Instead of adding the keys after the fact, could you use the `static` block in a component to define them, would be much easier, and it shouldnt complain then

2016-10-27 20:15 UTC, dingbat commented
@RealOrangeOne I'm not sure what you meant by using a `static` block, but I added the constants as static fields on the component class. Thanks for the good feedback.

2016-10-27 20:16 UTC, RealOrangeOne commented
Almost done. Can you remove the brackets around the fat-arrow functions, keep things a little cleaner, as they aren't needed. Then we can ship! :shipit:

2016-10-27 20:25 UTC, dingbat commented
Oh, the parentheses? They are needed because the functions return an empty object, so it's ambiguous with the omitted-bracket function syntax.

Actually now that I think about it, the library doesn't call the functions, it just references/asserts that they're present, so we could even just do:
```js
static CardStackPanResponder = CardStackPanResponder;
static CardStackStyleInterpolator = {
  forHorizontal: {},
  forVertical: {},
};
static PagerPanResponder = PagerPanResponder;
static PagerStyleInterpolator = {
  forHorizontal: {},
};
```

2016-10-28 07:59 UTC, RealOrangeOne commented
ah, didnt realise they were returning empty objects. thought they werent returning. In that case! :shipit:

2016-10-28 07:59 UTC, RealOrangeOne approved these changes

2016-10-28 07:59 UTC, merged