Add mock for Share API
lelandrichardson/react-native-mock pull request #128
Opened 2017-04-05 15:05 UTC by m-vdb

Hi there,

This is the mock for the [Share API](https://facebook.github.io/react-native/docs/share.html).

Cheers!

2017-04-05 15:40 UTC, RealOrangeOne requested changes
Great work!

Couple comments (both the same).

Also, please fix linter. See travis logs for exact errors

2017-04-05 15:40 UTC, RealOrangeOne commented on src/api/Share.js
> +  static get sharedAction() { return 'sharedAction'; }
Could this drop to multiple lines, or use fat-arrow syntax.

2017-04-05 15:40 UTC, RealOrangeOne commented on src/api/Share.js
> +  static get dismissedAction() { return 'dismissedAction'; }
Could this drop to multiple lines, or use fat-arrow syntax.

2017-04-05 20:00 UTC, m-vdb commented
thanks @RealOrangeOne it should be good with: f19363e

2017-04-06 08:08 UTC, RealOrangeOne approved these changes

2017-04-07 15:45 UTC, merged