add TouchableNativeFeedback mock
lelandrichardson/react-native-mock pull request #98
Opened 2016-09-21 12:28 UTC by lulutia

add TouchableNativeFeedback mock

2016-09-21 16:41 UTC, RealOrangeOne commented on src/react-native.js
> +ReactNative.PickerIOS.Item = createMockComponent('PickerIOS.Item');
Why is this line part of this PR?

2016-09-21 16:41 UTC, RealOrangeOne requested changes

2016-09-22 02:20 UTC, lulutia commented on src/react-native.js
> +ReactNative.PickerIOS.Item = createMockComponent('PickerIOS.Item');
This is the code i mentioned last PR, however, it has nothing to do with this PR, I can delete it.

2016-09-22 06:25 UTC, RealOrangeOne approved these changes

2016-09-22 06:26 UTC, merged